### ISSUE TITLE
效果好么

### ISSUE THREAD

**Issue by cokeshao** [Franfee/Robocom2022CAIP-ML-LSTNet-RoomTemperature-Pred#1]
我在mo平台上复现您的工作效果并不是很好，是我哪里操作不对么？

**Comment by Franfee** [comment]
我在自己测试效果也很一般，比赛看不见测试集。我不是做时序方向的，这个项目可能只能做参考，预测那里可能还需要改下

**Comment by Franfee** [comment]
> 我在自己测试效果也很一般，比赛看不见测试集。我不是做时序方向的，这个项目可能只能做参考，预测那里可能还需要改下

我在自己测试效果也很一般，比赛看不见测试集。我不是做时序方向的，这个项目可能只能做参考，预测那里可能还需要改下

**Comment by Franfee** [comment]
> 我在mo平台上复现您的工作效果并不是很好，是我哪里操作不对么？

我在自己测试效果也很一般，比赛看不见测试集。我不是做时序方向的，这个项目可能只能做参考，预测那里可能还需要改下
